export const loginConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const forgotPasswordConstants = {
  FORGOT_PASSWORD_IF_EXIST:"FORGOT_PASSWORD_IF_EXIST"
};

export const registerConstants = {
  SEND_MAIL_OTP:"SEND_MAIL_OTP",
  SET_OTP_MATCHED:"SET_OTP_MATCHED",
  SET_NAME:"SET_NAME",
  SET_DOB:"SET_DOB",
  SET_ROLE:"SET_ROLE",
  SET_PHONE:"SET_PHONE",
  SET_EMAIL:"SET_EMAIL",
  SET_REG_ERROR_EXIST:"SET_REG_ERROR_EXIST",
  SET_REG_ERROR_FAILED:"SET_REG_ERROR_FAILED",
  SET_REG_SUCCESS:"SET_REG_SUCCESS",
};

export const miscConstants = {
  ADD_TOKEN:"ADD_TOKEN"
};
