export const loginConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const forgotPasswordConstants = {
  FORGOT_PASSWORD_IF_EXIST:"FORGOT_PASSWORD_IF_EXIST"
};

export const miscConstants = {
  ADD_TOKEN:"ADD_TOKEN"
};
